services:
  marketplace:
    build:
      context: .
      dockerfile: marketplace/Dockerfile
    environment:
      RECOMMENDATIONS HOST: recommendations
    image: marketplace
    networks:
      - microservices
    ports:
      - 5001:5001
  
  recommendations:
    build:
      context: .
      dockerfile: recommendations/Dockerfile
    image: recommendations
    networks:
      - microservices
    
networks:
  microservices: